// web_frontend/src/lib/components/Button.svelte
<script lang="ts">
    import Icon from "./Icon.svelte";

    type Props = {
        readonly label: string;
        readonly onClick: () => void;
        readonly icon: "next" | "pause" | "play";
    };

    const { label, onClick, icon }: Props = $props();
</script>

<style>
    button {
        background-color: rgb(99 102 241);
        color: white;
        margin-top: 0.5rem;
        margin-bottom: 0.5rem;
        display: flex;
        justify-content: center;
        gap: 0.25rem;
    }
</style>

<button onclick={onClick}>
    <Icon {icon} /> {label}
</button>

// game_of_life_frontend/src/components/Button.tsx
import type { ReactElement } from "react";
import { Icon } from "./Icon";

type Props = {
    readonly label: string;
    readonly onClick: () => void;
    readonly icon: "next" | "pause" | "play";
};

export function Button({ label, onClick, icon }: Props): ReactElement {
    return (
        <button
            className="bg-indigo-500 text-white shadow my-2 rounded flex justify-center gap-1"
            onClick={onClick}
        >
            <Icon icon={icon} />
            {label}
        </button>
    );
}
